package Model;
// Generated May 25, 2016 7:51:48 AM by Hibernate Tools 4.3.1


import Controller.HibernateUtil;
import java.util.Date;
import java.util.List;
import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.Session;

/**
 * Score generated by hbm2java
 */
public class Score  implements java.io.Serializable {


     private Integer id;
     private Deck deck;
     private User user;
     private Float score;
     private Date dateAttempt;

    public Score() {
    }

    @Override
    public String toString()
    {
        return "{\"id\":\""+this.id+"\",\"id_deck\":\""+this.deck.getId()+"\",\"id_user\":\""+this.user.getId()+"\",\"score\":\""+this.score+"\",\"date_attempt\":\""+this.dateAttempt+"\"}";
    }
	
    public Score(Date dateAttempt) {
        this.dateAttempt = dateAttempt;
    }
    public Score(Deck deck, User user, Float score, Date dateAttempt) {
       this.deck = deck;
       this.user = user;
       this.score = score;
       this.dateAttempt = dateAttempt;
    }
    
    public List<Score> scores(User user) {
        String query = "from Score where id_user="+user.getId();
        List<Score> list = executeHQLQuery(query);
        return list;
    }
    
    private List executeHQLQuery(String hql) 
    {
        try 
        {
            Session session = HibernateUtil.getSessionFactory().openSession();
            session.beginTransaction();
            Query q = session.createQuery(hql);
            List resultList = q.list();
            session.getTransaction().commit();
            return resultList;
        } 
        catch (HibernateException he) 
        {
            he.printStackTrace();
        }
        return null;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Deck getDeck() {
        return this.deck;
    }
    
    public void setDeck(Deck deck) {
        this.deck = deck;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Float getScore() {
        return this.score;
    }
    
    public void setScore(Float score) {
        this.score = score;
    }
    public Date getDateAttempt() {
        return this.dateAttempt;
    }
    
    public void setDateAttempt(Date dateAttempt) {
        this.dateAttempt = dateAttempt;
    }




}


