package Model;
// Generated May 25, 2016 7:51:48 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Score generated by hbm2java
 */
public class Score  implements java.io.Serializable {


     private Integer id;
     private Deck deck;
     private User user;
     private Float score;
     private Date dateAttempt;

    public Score() {
    }

	
    public Score(Date dateAttempt) {
        this.dateAttempt = dateAttempt;
    }
    public Score(Deck deck, User user, Float score, Date dateAttempt) {
       this.deck = deck;
       this.user = user;
       this.score = score;
       this.dateAttempt = dateAttempt;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Deck getDeck() {
        return this.deck;
    }
    
    public void setDeck(Deck deck) {
        this.deck = deck;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Float getScore() {
        return this.score;
    }
    
    public void setScore(Float score) {
        this.score = score;
    }
    public Date getDateAttempt() {
        return this.dateAttempt;
    }
    
    public void setDateAttempt(Date dateAttempt) {
        this.dateAttempt = dateAttempt;
    }




}


