package Model;
// Generated May 25, 2016 7:51:48 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private String nameUser;
     private String password;
     private Date dateCreated;
     private String email;
     private Set decks = new HashSet(0);
     private Set scores = new HashSet(0);

    public User() {
    }

	
    public User(String nameUser, String password, Date dateCreated, String email) {
        this.nameUser = nameUser;
        this.password = password;
        this.dateCreated = dateCreated;
        this.email = email;
    }
    public User(String nameUser, String password, Date dateCreated, String email, Set decks, Set scores) {
       this.nameUser = nameUser;
       this.password = password;
       this.dateCreated = dateCreated;
       this.email = email;
       this.decks = decks;
       this.scores = scores;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNameUser() {
        return this.nameUser;
    }
    
    public void setNameUser(String nameUser) {
        this.nameUser = nameUser;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getDecks() {
        return this.decks;
    }
    
    public void setDecks(Set decks) {
        this.decks = decks;
    }
    public Set getScores() {
        return this.scores;
    }
    
    public void setScores(Set scores) {
        this.scores = scores;
    }




}


